
import type { NextPage } from 'next'
import Head from 'next/head'

import { useState } from 'react';
import Square from '../components/square';

type Board = number[];

const Home: NextPage = () => {
  const [board, setBoard] = useState<Board>(Array.apply(null, Array(64)).map(_ => 0));
  return (
    <main className='p-2 grid grid-cols-8 grid-rows-8 gap-2 w-max'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {board.map((item, index) => ( 
        <Square key={index} dark={Math.floor(index / 8) % 2 === 0} />
       ))}
    </main>
  )
}

export default Home
